content: |-
  ## Examples
  {{- if (file.IsDir "examples") -}}
  {{- range $example := (file.ReadDir "examples") }}
    ### Example {{ $example }}
    ```
    {{ include (printf "examples/%s/main.tf" $example) }}
    ```
  {{- end -}}
  {{- end -}}
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
