content: |-
  ## Examples
  {{- $examples := list "first" -}}
  {{- range $example := $examples -}}
    ### Example {{ $example }}
    ```
    {{ include (printf "examples/%s/main.tf" $example) }}
    ```

  {{ end -}}
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
